GitHub Actions: try to fix end to end test issue on MacOS

diff --git a/.github/workflows/end_to_end_test.yml b/.github/workflows/end_to_end_test.yml
--- a/.github/workflows/end_to_end_test.yml
+++ b/.github/workflows/end_to_end_test.yml
@@ -15,6 +15,10 @@ jobs:
     runs-on: ${{matrix.os}}
 
     steps:
+      - if: matrix.os == 'macos-latest'
+        name: Clear .NET Cache
+        run: rm -rf ~/.dotnet
+
       - name: Checkout code
         uses: actions/checkout@v2
 
@@ -40,10 +44,18 @@ jobs:
         run: |
           mkdir bin
           dotnet publish -r osx-x64 --self-contained true -p:PublishSingleFile=true -o bin -c Release Honeydew/Honeydew.csproj
-      
+
       - if: matrix.os == 'macos-latest'
         name: Display .NET Version Information
         run: dotnet --info
+
+      - if: matrix.os == 'macos-latest'
+        name: Check for file
+        run: |
+          if [ ! -f "/Users/runner/.dotnet/host/fxr/libhostfxr.dylib" ]; then
+            echo "libhostfxr.dylib is missing";
+            exit 1;
+          fi
 
       - name: Checkout Test Project
         uses: actions/checkout@v2
